import React from 'react'
import { MetaData } from '../MetaData'
export const Support = () => {
  return (
    <>  
    <MetaData title={"Support"} />
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ea repudiandae minus odio sit. Ipsum officia ab omnis necessitatibus cum asperiores deserunt voluptatum dignissimos voluptates. Officia autem repudiandae neque vero! Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint non eligendi ex unde laboriosam, placeat iure quis, numquam soluta obcaecati necessitatibus fuga veniam reiciendis! Ullam autem placeat excepturi, obcaecati repellendus minus nostrum quibusdam! Magni ea qui tenetur nemo asperiores, sunt veniam est suscipit vitae. Consequuntur facere fugit minima cupiditate aspernatur iure possimus ad ratione eveniet iste, laboriosam assumenda aut temporibus totam dignissimos, quisquam magni autem. Quidem nisi deleniti quis a adipisci sequi culpa similique earum soluta rerum et dolorem voluptatibus, hic dolor recusandae illum aut suscipit ullam, cupiditate minima explicabo iste vitae iusto porro? Sint facere voluptates ipsam labore, ab omnis vero. Recusandae, temporibus dignissimos. Sint sapiente fuga eaque culpa corporis nesciunt itaque aut? Neque ullam commodi velit magnam a cum animi inventore deleniti unde harum nemo alias deserunt, eaque mollitia maxime fuga voluptates explicabo hic aut? Ea voluptatibus laboriosam modi nemo nisi ullam sequi porro totam. In, cumque possimus voluptatum tempore saepe ipsam voluptates facere quae ducimus aliquid, qui laboriosam commodi neque vel, quos repellendus dolores totam blanditiis deserunt. Cumque eum aliquid dolorum animi doloremque explicabo ullam eos? Corrupti quae dolor exercitationem voluptatum molestiae itaque labore, aperiam dicta a totam sint ut aut ratione impedit nisi rerum saepe voluptas quas vel ipsum praesentium, eveniet aspernatur! Eum ipsum dolorum ea necessitatibus maxime soluta, non quam commodi quas fuga dolore, officia praesentium distinctio esse expedita. Rem, illo numquam, autem nulla ea assumenda at quibusdam non odio consectetur fugit exercitationem nobis incidunt. Illum modi fuga excepturi itaque eligendi iure aliquam fugiat soluta nobis veritatis blanditiis, molestiae expedita pariatur at quae dicta non quas vero exercitationem rerum libero. Minima itaque error laudantium inventore accusamus quia? Magnam minus accusamus distinctio iusto eum ut repellat sequi incidunt asperiores architecto possimus, officia laudantium repudiandae nostrum quasi reiciendis laborum! Nam ea tenetur voluptas minus numquam. Esse, aperiam.
    </>
  )
}
